"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import example.example_proto.demo.diff_pkg_refer_1_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Demo2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class MyFieldEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    MYFIELD_FIELD_NUMBER: builtins.int
    @property
    def myField(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1]: ...
    def __init__(self,
        *,
        myField: typing.Optional[typing.Mapping[typing.Text, example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["myField",b"myField"]) -> None: ...
global___Demo2 = Demo2
