# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_proto/demo/nested_enum_scope.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example/example_proto/demo/nested_enum_scope.proto',
  package='nested_enum_scope',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2example/example_proto/demo/nested_enum_scope.proto\x12\x11nested_enum_scope\"\xf1\x02\n\x0fVehiclePosition\x12L\n\x10occupancy_status\x18\x01 \x01(\x0e\x32\x32.nested_enum_scope.VehiclePosition.OccupancyStatus\x12R\n\x16multi_carriage_details\x18\x02 \x03(\x0b\x32\x32.nested_enum_scope.VehiclePosition.CarriageDetails\x1ak\n\x0f\x43\x61rriageDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12L\n\x10occupancy_status\x18\x02 \x01(\x0e\x32\x32.nested_enum_scope.VehiclePosition.OccupancyStatus\"O\n\x0fOccupancyStatus\x12\t\n\x05\x45MPTY\x10\x00\x12\x18\n\x14MANY_SEATS_AVAILABLE\x10\x01\x12\x17\n\x13\x46\x45W_SEATS_AVAILABLE\x10\x02\"B\n\x0b\x46\x65\x65\x64Message\x12\x33\n\x07vehicle\x18\x01 \x01(\x0b\x32\".nested_enum_scope.VehiclePositionb\x06proto3'
)



_VEHICLEPOSITION_OCCUPANCYSTATUS = _descriptor.EnumDescriptor(
  name='OccupancyStatus',
  full_name='nested_enum_scope.VehiclePosition.OccupancyStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMPTY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANY_SEATS_AVAILABLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEW_SEATS_AVAILABLE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=364,
  serialized_end=443,
)
_sym_db.RegisterEnumDescriptor(_VEHICLEPOSITION_OCCUPANCYSTATUS)


_VEHICLEPOSITION_CARRIAGEDETAILS = _descriptor.Descriptor(
  name='CarriageDetails',
  full_name='nested_enum_scope.VehiclePosition.CarriageDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nested_enum_scope.VehiclePosition.CarriageDetails.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='occupancy_status', full_name='nested_enum_scope.VehiclePosition.CarriageDetails.occupancy_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=362,
)

_VEHICLEPOSITION = _descriptor.Descriptor(
  name='VehiclePosition',
  full_name='nested_enum_scope.VehiclePosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='occupancy_status', full_name='nested_enum_scope.VehiclePosition.occupancy_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multi_carriage_details', full_name='nested_enum_scope.VehiclePosition.multi_carriage_details', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VEHICLEPOSITION_CARRIAGEDETAILS, ],
  enum_types=[
    _VEHICLEPOSITION_OCCUPANCYSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=443,
)


_FEEDMESSAGE = _descriptor.Descriptor(
  name='FeedMessage',
  full_name='nested_enum_scope.FeedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='nested_enum_scope.FeedMessage.vehicle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=511,
)

_VEHICLEPOSITION_CARRIAGEDETAILS.fields_by_name['occupancy_status'].enum_type = _VEHICLEPOSITION_OCCUPANCYSTATUS
_VEHICLEPOSITION_CARRIAGEDETAILS.containing_type = _VEHICLEPOSITION
_VEHICLEPOSITION.fields_by_name['occupancy_status'].enum_type = _VEHICLEPOSITION_OCCUPANCYSTATUS
_VEHICLEPOSITION.fields_by_name['multi_carriage_details'].message_type = _VEHICLEPOSITION_CARRIAGEDETAILS
_VEHICLEPOSITION_OCCUPANCYSTATUS.containing_type = _VEHICLEPOSITION
_FEEDMESSAGE.fields_by_name['vehicle'].message_type = _VEHICLEPOSITION
DESCRIPTOR.message_types_by_name['VehiclePosition'] = _VEHICLEPOSITION
DESCRIPTOR.message_types_by_name['FeedMessage'] = _FEEDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehiclePosition = _reflection.GeneratedProtocolMessageType('VehiclePosition', (_message.Message,), {

  'CarriageDetails' : _reflection.GeneratedProtocolMessageType('CarriageDetails', (_message.Message,), {
    'DESCRIPTOR' : _VEHICLEPOSITION_CARRIAGEDETAILS,
    '__module__' : 'example.example_proto.demo.nested_enum_scope_pb2'
    # @@protoc_insertion_point(class_scope:nested_enum_scope.VehiclePosition.CarriageDetails)
    })
  ,
  'DESCRIPTOR' : _VEHICLEPOSITION,
  '__module__' : 'example.example_proto.demo.nested_enum_scope_pb2'
  # @@protoc_insertion_point(class_scope:nested_enum_scope.VehiclePosition)
  })
_sym_db.RegisterMessage(VehiclePosition)
_sym_db.RegisterMessage(VehiclePosition.CarriageDetails)

FeedMessage = _reflection.GeneratedProtocolMessageType('FeedMessage', (_message.Message,), {
  'DESCRIPTOR' : _FEEDMESSAGE,
  '__module__' : 'example.example_proto.demo.nested_enum_scope_pb2'
  # @@protoc_insertion_point(class_scope:nested_enum_scope.FeedMessage)
  })
_sym_db.RegisterMessage(FeedMessage)


# @@protoc_insertion_point(module_scope)
