# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from example.example_grpc.python_example_proto_code.example_proto.book import social_pb2 as example__proto_dot_book_dot_social__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BookSocialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.like_book = channel.unary_unary(
                '/book_social.BookSocial/like_book',
                request_serializer=example__proto_dot_book_dot_social__pb2.LikeBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.like_multi_book = channel.unary_unary(
                '/book_social.BookSocial/like_multi_book',
                request_serializer=example__proto_dot_book_dot_social__pb2.LikeBookMapRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.get_book_like = channel.unary_unary(
                '/book_social.BookSocial/get_book_like',
                request_serializer=example__proto_dot_book_dot_social__pb2.GetBookLikesRequest.SerializeToString,
                response_deserializer=example__proto_dot_book_dot_social__pb2.GetBookLikesListResult.FromString,
                )
        self.comment_book = channel.unary_unary(
                '/book_social.BookSocial/comment_book',
                request_serializer=example__proto_dot_book_dot_social__pb2.CommentBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.get_book_comment = channel.unary_unary(
                '/book_social.BookSocial/get_book_comment',
                request_serializer=example__proto_dot_book_dot_social__pb2.GetBookCommentRequest.SerializeToString,
                response_deserializer=example__proto_dot_book_dot_social__pb2.GetBookCommentListResult.FromString,
                )


class BookSocialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def like_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def like_multi_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_book_like(self, request, context):
        """pait: {"http_method": "GET"}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def comment_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_book_comment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookSocialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'like_book': grpc.unary_unary_rpc_method_handler(
                    servicer.like_book,
                    request_deserializer=example__proto_dot_book_dot_social__pb2.LikeBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'like_multi_book': grpc.unary_unary_rpc_method_handler(
                    servicer.like_multi_book,
                    request_deserializer=example__proto_dot_book_dot_social__pb2.LikeBookMapRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_book_like': grpc.unary_unary_rpc_method_handler(
                    servicer.get_book_like,
                    request_deserializer=example__proto_dot_book_dot_social__pb2.GetBookLikesRequest.FromString,
                    response_serializer=example__proto_dot_book_dot_social__pb2.GetBookLikesListResult.SerializeToString,
            ),
            'comment_book': grpc.unary_unary_rpc_method_handler(
                    servicer.comment_book,
                    request_deserializer=example__proto_dot_book_dot_social__pb2.CommentBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_book_comment': grpc.unary_unary_rpc_method_handler(
                    servicer.get_book_comment,
                    request_deserializer=example__proto_dot_book_dot_social__pb2.GetBookCommentRequest.FromString,
                    response_serializer=example__proto_dot_book_dot_social__pb2.GetBookCommentListResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book_social.BookSocial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookSocial(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def like_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_social.BookSocial/like_book',
            example__proto_dot_book_dot_social__pb2.LikeBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def like_multi_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_social.BookSocial/like_multi_book',
            example__proto_dot_book_dot_social__pb2.LikeBookMapRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_book_like(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_social.BookSocial/get_book_like',
            example__proto_dot_book_dot_social__pb2.GetBookLikesRequest.SerializeToString,
            example__proto_dot_book_dot_social__pb2.GetBookLikesListResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def comment_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_social.BookSocial/comment_book',
            example__proto_dot_book_dot_social__pb2.CommentBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_book_comment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_social.BookSocial/get_book_comment',
            example__proto_dot_book_dot_social__pb2.GetBookCommentRequest.SerializeToString,
            example__proto_dot_book_dot_social__pb2.GetBookCommentListResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
