# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_proto/test_ignore/main_pkg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from example.proto_pydanticv2.example.example_proto.test_ignore import ignored_pkg_pb2 as example_dot_example__proto_dot_test__ignore_dot_ignored__pkg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0example/example_proto/test_ignore/main_pkg.proto\x12\x14test_ignore.main_pkg\x1a\x33\x65xample/example_proto/test_ignore/ignored_pkg.proto\"\x9f\x01\n\x0bMainMessage\x12\x14\n\x0cnormal_field\x18\x01 \x01(\t\x12>\n\rignored_field\x18\x02 \x01(\x0b\x32\'.test_ignore.ignored_pkg.IgnoredMessage\x12:\n\x0cignored_enum\x18\x03 \x01(\x0e\x32$.test_ignore.ignored_pkg.IgnoredEnumb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.example_proto.test_ignore.main_pkg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAINMESSAGE._serialized_start=128
  _MAINMESSAGE._serialized_end=287
# @@protoc_insertion_point(module_scope)
