# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_proto/test_ignore/main_pkg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from example.proto_3_20_pydanticv1.example.example_proto.test_ignore import ignored_pkg_pb2 as example_dot_example__proto_dot_test__ignore_dot_ignored__pkg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example/example_proto/test_ignore/main_pkg.proto',
  package='test_ignore.main_pkg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0example/example_proto/test_ignore/main_pkg.proto\x12\x14test_ignore.main_pkg\x1a\x33\x65xample/example_proto/test_ignore/ignored_pkg.proto\"\x9f\x01\n\x0bMainMessage\x12\x14\n\x0cnormal_field\x18\x01 \x01(\t\x12>\n\rignored_field\x18\x02 \x01(\x0b\x32\'.test_ignore.ignored_pkg.IgnoredMessage\x12:\n\x0cignored_enum\x18\x03 \x01(\x0e\x32$.test_ignore.ignored_pkg.IgnoredEnumb\x06proto3'
  ,
  dependencies=[example_dot_example__proto_dot_test__ignore_dot_ignored__pkg__pb2.DESCRIPTOR,])




_MAINMESSAGE = _descriptor.Descriptor(
  name='MainMessage',
  full_name='test_ignore.main_pkg.MainMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='normal_field', full_name='test_ignore.main_pkg.MainMessage.normal_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ignored_field', full_name='test_ignore.main_pkg.MainMessage.ignored_field', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ignored_enum', full_name='test_ignore.main_pkg.MainMessage.ignored_enum', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=287,
)

_MAINMESSAGE.fields_by_name['ignored_field'].message_type = example_dot_example__proto_dot_test__ignore_dot_ignored__pkg__pb2._IGNOREDMESSAGE
_MAINMESSAGE.fields_by_name['ignored_enum'].enum_type = example_dot_example__proto_dot_test__ignore_dot_ignored__pkg__pb2._IGNOREDENUM
DESCRIPTOR.message_types_by_name['MainMessage'] = _MAINMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MainMessage = _reflection.GeneratedProtocolMessageType('MainMessage', (_message.Message,), {
  'DESCRIPTOR' : _MAINMESSAGE,
  '__module__' : 'example.example_proto.test_ignore.main_pkg_pb2'
  # @@protoc_insertion_point(class_scope:test_ignore.main_pkg.MainMessage)
  })
_sym_db.RegisterMessage(MainMessage)


# @@protoc_insertion_point(module_scope)
