# This is an automatically generated file, please do not change
# gen by protobuf_to_pydantic(https://github.com/so1n/protobuf_to_pydantic)
# type: ignore

import datetime
import typing

from google.protobuf.message import Message  # type: ignore
from protobuf_to_pydantic.util import Timedelta
from pydantic import BaseModel
from pydantic.fields import FieldInfo


class FieldRules(BaseModel):
    message: "MessageRules" = FieldInfo(extra={})
    float: "FloatRules" = FieldInfo(extra={})
    double: "DoubleRules" = FieldInfo(extra={})
    int32: "Int32Rules" = FieldInfo(extra={})
    int64: "Int64Rules" = FieldInfo(extra={})
    uint32: "UInt32Rules" = FieldInfo(extra={})
    uint64: "UInt64Rules" = FieldInfo(extra={})
    sint32: "SInt32Rules" = FieldInfo(extra={})
    sint64: "SInt64Rules" = FieldInfo(extra={})
    fixed32: "Fixed32Rules" = FieldInfo(extra={})
    fixed64: "Fixed64Rules" = FieldInfo(extra={})
    sfixed32: "SFixed32Rules" = FieldInfo(extra={})
    sfixed64: "SFixed64Rules" = FieldInfo(extra={})
    bool: "BoolRules" = FieldInfo(extra={})
    string: "StringRules" = FieldInfo(extra={})
    bytes: "BytesRules" = FieldInfo(extra={})
    enum: "EnumRules" = FieldInfo(extra={})
    repeated: "RepeatedRules" = FieldInfo(extra={})
    map: "MapRules" = FieldInfo(extra={})
    any: "AnyRules" = FieldInfo(extra={})
    duration: "DurationRules" = FieldInfo(extra={})
    timestamp: "TimestampRules" = FieldInfo(extra={})


class FloatRules(BaseModel):
    const: float = FieldInfo(default=0.0, extra={})
    lt: float = FieldInfo(default=0.0, extra={})
    le: float = FieldInfo(default=0.0, extra={})
    gt: float = FieldInfo(default=0.0, extra={})
    ge: float = FieldInfo(default=0.0, extra={})
    not_in: typing.List[float] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class DoubleRules(BaseModel):
    const: float = FieldInfo(default=0.0, extra={})
    lt: float = FieldInfo(default=0.0, extra={})
    le: float = FieldInfo(default=0.0, extra={})
    gt: float = FieldInfo(default=0.0, extra={})
    ge: float = FieldInfo(default=0.0, extra={})
    not_in: typing.List[float] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class Int32Rules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    lt: int = FieldInfo(default=0, extra={})
    le: int = FieldInfo(default=0, extra={})
    gt: int = FieldInfo(default=0, extra={})
    ge: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class Int64Rules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    lt: int = FieldInfo(default=0, extra={})
    le: int = FieldInfo(default=0, extra={})
    gt: int = FieldInfo(default=0, extra={})
    ge: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class UInt32Rules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    lt: int = FieldInfo(default=0, extra={})
    le: int = FieldInfo(default=0, extra={})
    gt: int = FieldInfo(default=0, extra={})
    ge: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class UInt64Rules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    lt: int = FieldInfo(default=0, extra={})
    le: int = FieldInfo(default=0, extra={})
    gt: int = FieldInfo(default=0, extra={})
    ge: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class SInt32Rules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    lt: int = FieldInfo(default=0, extra={})
    le: int = FieldInfo(default=0, extra={})
    gt: int = FieldInfo(default=0, extra={})
    ge: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class SInt64Rules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    lt: int = FieldInfo(default=0, extra={})
    le: int = FieldInfo(default=0, extra={})
    gt: int = FieldInfo(default=0, extra={})
    ge: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class Fixed32Rules(BaseModel):
    const: float = FieldInfo(default=0.0, extra={})
    lt: float = FieldInfo(default=0.0, extra={})
    le: float = FieldInfo(default=0.0, extra={})
    gt: float = FieldInfo(default=0.0, extra={})
    ge: float = FieldInfo(default=0.0, extra={})
    not_in: typing.List[float] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class Fixed64Rules(BaseModel):
    const: float = FieldInfo(default=0.0, extra={})
    lt: float = FieldInfo(default=0.0, extra={})
    le: float = FieldInfo(default=0.0, extra={})
    gt: float = FieldInfo(default=0.0, extra={})
    ge: float = FieldInfo(default=0.0, extra={})
    not_in: typing.List[float] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class SFixed32Rules(BaseModel):
    const: float = FieldInfo(default=0.0, extra={})
    lt: float = FieldInfo(default=0.0, extra={})
    le: float = FieldInfo(default=0.0, extra={})
    gt: float = FieldInfo(default=0.0, extra={})
    ge: float = FieldInfo(default=0.0, extra={})
    not_in: typing.List[float] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class SFixed64Rules(BaseModel):
    const: float = FieldInfo(default=0.0, extra={})
    lt: float = FieldInfo(default=0.0, extra={})
    le: float = FieldInfo(default=0.0, extra={})
    gt: float = FieldInfo(default=0.0, extra={})
    ge: float = FieldInfo(default=0.0, extra={})
    not_in: typing.List[float] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class BoolRules(BaseModel):
    const: bool = FieldInfo(default=False, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: bool = FieldInfo(default=False, extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: bool = FieldInfo(default=False, extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class StringRules(BaseModel):
    const: str = FieldInfo(default="", extra={})
    len: int = FieldInfo(default=0, extra={})
    min_length: int = FieldInfo(default=0, extra={})
    max_length: int = FieldInfo(default=0, extra={})
    pattern: str = FieldInfo(default="", extra={})
    prefix: str = FieldInfo(default="", extra={})
    suffix: str = FieldInfo(default="", extra={})
    contains: str = FieldInfo(default="", extra={})
    not_contains: str = FieldInfo(default="", extra={})
    not_in: typing.List[str] = FieldInfo(default_factory=list, extra={})
    email: bool = FieldInfo(default=False, extra={})
    hostname: bool = FieldInfo(default=False, extra={})
    ip: bool = FieldInfo(default=False, extra={})
    ipv4: bool = FieldInfo(default=False, extra={})
    ipv6: bool = FieldInfo(default=False, extra={})
    uri: bool = FieldInfo(default=False, extra={})
    uri_ref: bool = FieldInfo(default=False, extra={})
    address: bool = FieldInfo(default=False, extra={})
    uuid: bool = FieldInfo(default=False, extra={})
    pydantic_type: str = FieldInfo(default="", extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: str = FieldInfo(default="", extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: str = FieldInfo(default="", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class BytesRules(BaseModel):
    const: bytes = FieldInfo(default=b"", extra={})
    min_length: int = FieldInfo(default=0, extra={})
    max_length: int = FieldInfo(default=0, extra={})
    prefix: bytes = FieldInfo(default=b"", extra={})
    suffix: bytes = FieldInfo(default=b"", extra={})
    contains: bytes = FieldInfo(default=b"", extra={})
    not_in: typing.List[bytes] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: bytes = FieldInfo(default=b"", extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    multiple_of: float = FieldInfo(default=0.0, extra={})
    example: bytes = FieldInfo(default=b"", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    ip: bool = FieldInfo(default=False, extra={})
    ipv4: bool = FieldInfo(default=False, extra={})
    ipv6: bool = FieldInfo(default=False, extra={})
    title: str = FieldInfo(default="", extra={})


class EnumRules(BaseModel):
    const: int = FieldInfo(default=0, extra={})
    not_in: typing.List[int] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: int = FieldInfo(default=0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: int = FieldInfo(default=0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class MessageRules(BaseModel):
    skip: bool = FieldInfo(default=False, extra={})
    required: bool = FieldInfo(default=False, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: float = FieldInfo(default=0.0, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: float = FieldInfo(default=0.0, extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class RepeatedRules(BaseModel):
    min_items: int = FieldInfo(default=0, extra={})
    max_items: int = FieldInfo(default=0, extra={})
    unique: bool = FieldInfo(default=False, extra={})
    items: "FieldRules" = FieldInfo(extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class MapRules(BaseModel):
    min_pairs: int = FieldInfo(default=0, extra={})
    max_pairs: int = FieldInfo(default=0, extra={})
    keys: "FieldRules" = FieldInfo(extra={})
    values: "FieldRules" = FieldInfo(extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class AnyRules(BaseModel):
    required: bool = FieldInfo(default=False, extra={})
    not_in: typing.List[str] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: str = FieldInfo(default="", extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: str = FieldInfo(default="", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class DurationRules(BaseModel):
    const: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    lt: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    le: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    gt: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    ge: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    not_in: typing.List[Timedelta] = FieldInfo(default_factory=list, extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})


class TimestampRules(BaseModel):
    const: datetime.datetime = FieldInfo(default_factory="now", extra={})
    lt: datetime.datetime = FieldInfo(default_factory="now", extra={})
    le: datetime.datetime = FieldInfo(default_factory="now", extra={})
    gt: datetime.datetime = FieldInfo(default_factory="now", extra={})
    ge: datetime.datetime = FieldInfo(default_factory="now", extra={})
    lt_now: bool = FieldInfo(default=False, extra={})
    gt_now: bool = FieldInfo(default=False, extra={})
    within: Timedelta = FieldInfo(default_factory="Timedelta", extra={})
    enable: bool = FieldInfo(default=False, extra={})
    default: datetime.datetime = FieldInfo(default_factory="now", extra={})
    default_factory: str = FieldInfo(default="", extra={})
    miss_default: bool = FieldInfo(default=False, extra={})
    alias: str = FieldInfo(default="", extra={})
    description: str = FieldInfo(default="", extra={})
    example: datetime.datetime = FieldInfo(default_factory="now", extra={})
    example_factory: str = FieldInfo(default="", extra={})
    field: str = FieldInfo(default="", extra={})
    type: str = FieldInfo(default="", extra={})
    title: str = FieldInfo(default="", extra={})
