# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_proto/common/single.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example_proto/common/single.proto',
  package='single',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!example_proto/common/single.proto\x12\x06single\";\n\x0b\x44\x65moMessage\x12\r\n\x05\x65\x61rth\x18\x01 \x01(\t\x12\x0f\n\x07mercury\x18\x02 \x01(\t\x12\x0c\n\x04mars\x18\x03 \x01(\t*&\n\x08\x44\x65moEnum\x12\x08\n\x04zero\x10\x00\x12\x07\n\x03one\x10\x01\x12\x07\n\x03two\x10\x03\x62\x06proto3'
)

_DEMOENUM = _descriptor.EnumDescriptor(
  name='DemoEnum',
  full_name='single.DemoEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='zero', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='one', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='two', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=106,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_DEMOENUM)

DemoEnum = enum_type_wrapper.EnumTypeWrapper(_DEMOENUM)
zero = 0
one = 1
two = 3



_DEMOMESSAGE = _descriptor.Descriptor(
  name='DemoMessage',
  full_name='single.DemoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='earth', full_name='single.DemoMessage.earth', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mercury', full_name='single.DemoMessage.mercury', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mars', full_name='single.DemoMessage.mars', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['DemoMessage'] = _DEMOMESSAGE
DESCRIPTOR.enum_types_by_name['DemoEnum'] = _DEMOENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DemoMessage = _reflection.GeneratedProtocolMessageType('DemoMessage', (_message.Message,), {
  'DESCRIPTOR' : _DEMOMESSAGE,
  '__module__' : 'example_proto.common.single_pb2'
  # @@protoc_insertion_point(class_scope:single.DemoMessage)
  })
_sym_db.RegisterMessage(DemoMessage)


# @@protoc_insertion_point(module_scope)
