"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class UserMessage(google.protobuf.message.Message):
    """user info"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UID_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    IS_ADULT_FIELD_NUMBER: builtins.int
    USER_NAME_FIELD_NUMBER: builtins.int
    uid: typing.Text
    """aha: {"required": true, "example": "10086", "title": "UID", "description": "user union id"}"""

    age: builtins.int
    """aha: {"example": 18, "title": "use age", "ge": 0}"""

    height: builtins.float
    """aha: {"ge": 0, "le": 2.5}
    user_height
    """

    is_adult: builtins.bool
    user_name: typing.Text
    """aha: {"description": "user name"}
    aha: {"default": "", "min_length": 1, "max_length": "10", "example": "so1n"}
    """

    def __init__(self,
        *,
        uid: typing.Text = ...,
        age: builtins.int = ...,
        height: builtins.float = ...,
        is_adult: builtins.bool = ...,
        user_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["age",b"age","height",b"height","is_adult",b"is_adult","uid",b"uid","user_name",b"user_name"]) -> None: ...
global___UserMessage = UserMessage
