# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_proto/demo/diff_pkg_refer_2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from example.proto_pydanticv1.example.example_proto.demo import diff_pkg_refer_1_pb2 as example_dot_example__proto_dot_demo_dot_diff__pkg__refer__1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1example/example_proto/demo/diff_pkg_refer_2.proto\x12\x10\x64iff_pkg_refer_2\x1a\x31\x65xample/example_proto/demo/diff_pkg_refer_1.proto\"\x87\x01\n\x05\x44\x65mo2\x12\x35\n\x07myField\x18\x01 \x03(\x0b\x32$.diff_pkg_refer_2.Demo2.MyFieldEntry\x1aG\n\x0cMyFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.diff_pkg_refer_1.Demo1:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.example_proto.demo.diff_pkg_refer_2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEMO2_MYFIELDENTRY._options = None
  _DEMO2_MYFIELDENTRY._serialized_options = b'8\001'
  _DEMO2._serialized_start=123
  _DEMO2._serialized_end=258
  _DEMO2_MYFIELDENTRY._serialized_start=187
  _DEMO2_MYFIELDENTRY._serialized_end=258
# @@protoc_insertion_point(module_scope)
