"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class VehiclePosition(google.protobuf.message.Message):
    """Reproduces sibling nested enum references used by nested messages."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _OccupancyStatus:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _OccupancyStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[VehiclePosition._OccupancyStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        EMPTY: VehiclePosition._OccupancyStatus.ValueType  # 0
        MANY_SEATS_AVAILABLE: VehiclePosition._OccupancyStatus.ValueType  # 1
        FEW_SEATS_AVAILABLE: VehiclePosition._OccupancyStatus.ValueType  # 2
    class OccupancyStatus(_OccupancyStatus, metaclass=_OccupancyStatusEnumTypeWrapper):
        pass

    EMPTY: VehiclePosition.OccupancyStatus.ValueType  # 0
    MANY_SEATS_AVAILABLE: VehiclePosition.OccupancyStatus.ValueType  # 1
    FEW_SEATS_AVAILABLE: VehiclePosition.OccupancyStatus.ValueType  # 2

    class CarriageDetails(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ID_FIELD_NUMBER: builtins.int
        OCCUPANCY_STATUS_FIELD_NUMBER: builtins.int
        id: typing.Text
        occupancy_status: global___VehiclePosition.OccupancyStatus.ValueType
        def __init__(self,
            *,
            id: typing.Text = ...,
            occupancy_status: global___VehiclePosition.OccupancyStatus.ValueType = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["id",b"id","occupancy_status",b"occupancy_status"]) -> None: ...

    OCCUPANCY_STATUS_FIELD_NUMBER: builtins.int
    MULTI_CARRIAGE_DETAILS_FIELD_NUMBER: builtins.int
    occupancy_status: global___VehiclePosition.OccupancyStatus.ValueType
    @property
    def multi_carriage_details(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VehiclePosition.CarriageDetails]: ...
    def __init__(self,
        *,
        occupancy_status: global___VehiclePosition.OccupancyStatus.ValueType = ...,
        multi_carriage_details: typing.Optional[typing.Iterable[global___VehiclePosition.CarriageDetails]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["multi_carriage_details",b"multi_carriage_details","occupancy_status",b"occupancy_status"]) -> None: ...
global___VehiclePosition = VehiclePosition

class FeedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VEHICLE_FIELD_NUMBER: builtins.int
    @property
    def vehicle(self) -> global___VehiclePosition: ...
    def __init__(self,
        *,
        vehicle: typing.Optional[global___VehiclePosition] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["vehicle",b"vehicle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["vehicle",b"vehicle"]) -> None: ...
global___FeedMessage = FeedMessage
