"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import example.example_proto.test_ignore.ignored_pkg_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class MainMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NORMAL_FIELD_FIELD_NUMBER: builtins.int
    IGNORED_FIELD_FIELD_NUMBER: builtins.int
    IGNORED_ENUM_FIELD_NUMBER: builtins.int
    normal_field: typing.Text
    """p2p: {"required": true}"""

    @property
    def ignored_field(self) -> example.example_proto.test_ignore.ignored_pkg_pb2.IgnoredMessage:
        """These types should be used but NOT imported due to ignore_pkg_list"""
        pass
    ignored_enum: example.example_proto.test_ignore.ignored_pkg_pb2.IgnoredEnum.ValueType
    def __init__(self,
        *,
        normal_field: typing.Text = ...,
        ignored_field: typing.Optional[example.example_proto.test_ignore.ignored_pkg_pb2.IgnoredMessage] = ...,
        ignored_enum: example.example_proto.test_ignore.ignored_pkg_pb2.IgnoredEnum.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ignored_field",b"ignored_field"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ignored_enum",b"ignored_enum","ignored_field",b"ignored_field","normal_field",b"normal_field"]) -> None: ...
global___MainMessage = MainMessage
