# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_proto/demo/alias_demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example/example_proto/demo/alias_demo.proto',
  package='alias_demo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+example/example_proto/demo/alias_demo.proto\x12\nalias_demo\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n\nReportData\x12\x31\n\x0elocation_value\x18\x05 \x01(\x0b\x32\x17.alias_demo.GeoLocationH\x00\x12\x30\n\ntime_value\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x42\x06\n\x04\x64\x61ta\"d\n\x0bGeoLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x1c\n\x0f\x61ltitude_meters\x18\x03 \x01(\x01H\x00\x88\x01\x01\x42\x12\n\x10_altitude_meters\"T\n\x06Report\x12\x16\n\tsource_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12$\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x16.alias_demo.ReportDataB\x0c\n\n_source_idb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_REPORTDATA = _descriptor.Descriptor(
  name='ReportData',
  full_name='alias_demo.ReportData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location_value', full_name='alias_demo.ReportData.location_value', index=0,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_value', full_name='alias_demo.ReportData.time_value', index=1,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='alias_demo.ReportData.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=92,
  serialized_end=213,
)


_GEOLOCATION = _descriptor.Descriptor(
  name='GeoLocation',
  full_name='alias_demo.GeoLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='alias_demo.GeoLocation.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='alias_demo.GeoLocation.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude_meters', full_name='alias_demo.GeoLocation.altitude_meters', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_altitude_meters', full_name='alias_demo.GeoLocation._altitude_meters',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=215,
  serialized_end=315,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='alias_demo.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_id', full_name='alias_demo.Report.source_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='alias_demo.Report.data', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_source_id', full_name='alias_demo.Report._source_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=317,
  serialized_end=401,
)

_REPORTDATA.fields_by_name['location_value'].message_type = _GEOLOCATION
_REPORTDATA.fields_by_name['time_value'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REPORTDATA.oneofs_by_name['data'].fields.append(
  _REPORTDATA.fields_by_name['location_value'])
_REPORTDATA.fields_by_name['location_value'].containing_oneof = _REPORTDATA.oneofs_by_name['data']
_REPORTDATA.oneofs_by_name['data'].fields.append(
  _REPORTDATA.fields_by_name['time_value'])
_REPORTDATA.fields_by_name['time_value'].containing_oneof = _REPORTDATA.oneofs_by_name['data']
_GEOLOCATION.oneofs_by_name['_altitude_meters'].fields.append(
  _GEOLOCATION.fields_by_name['altitude_meters'])
_GEOLOCATION.fields_by_name['altitude_meters'].containing_oneof = _GEOLOCATION.oneofs_by_name['_altitude_meters']
_REPORT.fields_by_name['data'].message_type = _REPORTDATA
_REPORT.oneofs_by_name['_source_id'].fields.append(
  _REPORT.fields_by_name['source_id'])
_REPORT.fields_by_name['source_id'].containing_oneof = _REPORT.oneofs_by_name['_source_id']
DESCRIPTOR.message_types_by_name['ReportData'] = _REPORTDATA
DESCRIPTOR.message_types_by_name['GeoLocation'] = _GEOLOCATION
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReportData = _reflection.GeneratedProtocolMessageType('ReportData', (_message.Message,), {
  'DESCRIPTOR' : _REPORTDATA,
  '__module__' : 'example.example_proto.demo.alias_demo_pb2'
  # @@protoc_insertion_point(class_scope:alias_demo.ReportData)
  })
_sym_db.RegisterMessage(ReportData)

GeoLocation = _reflection.GeneratedProtocolMessageType('GeoLocation', (_message.Message,), {
  'DESCRIPTOR' : _GEOLOCATION,
  '__module__' : 'example.example_proto.demo.alias_demo_pb2'
  # @@protoc_insertion_point(class_scope:alias_demo.GeoLocation)
  })
_sym_db.RegisterMessage(GeoLocation)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'example.example_proto.demo.alias_demo_pb2'
  # @@protoc_insertion_point(class_scope:alias_demo.Report)
  })
_sym_db.RegisterMessage(Report)


# @@protoc_insertion_point(module_scope)
