# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_proto/demo/diff_pkg_refer_1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example/example_proto/demo/diff_pkg_refer_1.proto',
  package='diff_pkg_refer_1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1example/example_proto/demo/diff_pkg_refer_1.proto\x12\x10\x64iff_pkg_refer_1\"\x07\n\x05\x44\x65mo1b\x06proto3'
)




_DEMO1 = _descriptor.Descriptor(
  name='Demo1',
  full_name='diff_pkg_refer_1.Demo1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['Demo1'] = _DEMO1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Demo1 = _reflection.GeneratedProtocolMessageType('Demo1', (_message.Message,), {
  'DESCRIPTOR' : _DEMO1,
  '__module__' : 'example.example_proto.demo.diff_pkg_refer_1_pb2'
  # @@protoc_insertion_point(class_scope:diff_pkg_refer_1.Demo1)
  })
_sym_db.RegisterMessage(Demo1)


# @@protoc_insertion_point(module_scope)
